import { StylesConfig } from "react-select";

export const customStylesSelect: StylesConfig<any> = {
  placeholder: (provided) => ({
    ...provided,
    color: "white",
    fontFamily: "Montserrat, sans-serif",
    margin: 0,
  }),
  singleValue: (provided) => ({
    ...provided,
    color: "white",
    padding: 0,
    display: "flex",
    alignItems: "center",
  }),
  control: (provided) => ({
    ...provided,
    display: "flex",
    alignItems: "center",
    borderRadius: "none",
    border: "none",
    boxShadow: "none",
    height: "5rem",
    padding: "0 1rem",
    fontSize: "1.5rem",
    color: "white",
    cursor: "pointer",
    "&:hover": {
      border: "none",
    },
  }),
  menu: (provided) => ({
    ...provided,
    marginTop: 0,
    borderRadius: "none",
    border: "none",
    boxShadow: "none",
    // backgroundColor: "#4C9BF8",
    padding: "0",
  }),
  menuList: (provided) => ({
    ...provided,
    maxHeight: "16rem",
    overflowY: "auto",
    scrollbarWidth: "none",
    WebkitOverflowScrolling: "touch",
    padding: 0,
    margin: 0,
    borderRadius: "none",
    // backgroundColor: "#4C9BF8",
    // borderBottom: ".5rem solid #EDEBEB",
  }),
  valueContainer: (provided) => ({
    ...provided,
    display: "flex",
    alignItems: "center",
    padding: 0,
  }),
  option: (provided) => ({
    ...provided,
    display: "flex",
    justifyContent: "center",
    borderRadius: "none",
    color: "white",
    padding: "1.5rem 2.3rem",
    fontSize: "1.5rem",
    fontWeight: "normal",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: "#FFFFFF",
    },
  }),
  dropdownIndicator: (provided) => ({
    ...provided,
    display: "flex",
    alignItems: "center",
    color: "#4D9EFE",
    padding: 0,
    transition: "color 0.2s ease",
    "&:hover": {
      color: "white",
    },
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
};
